[package]
name = "app_core"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonwebtoken = "9.3.0"
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15"
once_cell = "1.19"
serde_json = "1.0"
sd-jwt-rs = "0.7.1"
ring = "0.17"
base64 = "0.21"
yasna = "0.5"
