[package]
name = "verifier_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
sd-jwt-rs = "0.7.1"

app_core = { path = "../app_core" }